default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/obyavlyay_development.sqlite3

test:
  <<: *default
  database: db/obyavlyay_test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: obyavlyay_production
  username: obyavlyay
  password: <%= ENV["RAILS_PROJECT_65_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
